### PR TITLE
Git hook

### PR DESCRIPTION
**Pull request by mkristien**
## Description
We want to disallow commitsthat do not pass the same tests used by travis.

For fast prototyping, people can always force their way through by using `git commit --no-verify`

### CODE REVIEW

**Comment by brano2** [comment]
How long do the tests take to execute? From my experience, it starts to get annoying at around 10 seconds. If I have to wait any significant amount of time every time I want to commit, it encourages larger and messier commits so there needs to be a trade-off.
Also, as we add more tests, it will likely get slower, right? Any plans for only running a (small) subset of tests on the commit hook and the full set on travis?
Are there push hooks? Maybe we could use those for stuff that takes too long for commit hooks.

**Comment by mkristien** [comment]
I understand. We can use push hooks instead. This would mean people can commit whatever but cannot "share" by pushing if it does not pass some testing (e.g. does not compile).

In QA, what we have in mind is to have multiple tier testing systems. Even in the `Makefile`, `make test` should expose only some user-friendly (in terms of runtime) testing. Other more involved/longer test will be defined in `test/Makefile`. Those might be used in travis, for example.

At the moment, the testing runs almost instantly (less than a second). Let me know what you want to have in the hook (e.g. `src/` has to compile and link, `test/src/` compiles and links, running tests succeeds, linter `src/` succeeds, `lintall` succeeds, or any subset of these). Also, let me know if you want this hook to be only for pushes.

**Comment by brano2** [comment]
Ok, sounds good. My only worry is that we don't actually manage to set up the different tiers of tests for some reason. I have looked into something like that before for Python and it can be quite tricky. (There are different and conflicting requirements for tiers. For example, do we split by running time or conceptually like unit tests / integration tests / ...?) Unless you really have all of this figured out in QA, I'd like the pre-commit hook to only compile, link, and lint everything (i.e. `src/` and `test/src/`) and the pre-push hook to run the tests and check they succeed. Later we can move some quick tests to the pre-commit hook as well.

**Review by brano2 — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
